/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AllVoteChart: typeof import('./src/components/section/AllVoteChart.vue')['default']
    Banner: typeof import('./src/components/section/Banner.vue')['default']
    BarChart: typeof import('./src/components/Chart/BarChart.vue')['default']
    BarChat: typeof import('./src/components/BarChat.vue')['default']
    Candidate: typeof import('./src/components/section/Candidate.vue')['default']
    County: typeof import('./src/components/Map/County.vue')['default']
    Dropdown: typeof import('./src/components/Dropdown.vue')['default']
    GroupBarChart: typeof import('./src/components/Chart/GroupBarChart.vue')['default']
    LineChart: typeof import('./src/components/Chart/LineChart.vue')['default']
    MYFooter: typeof import('./src/components/layout/MYFooter.vue')['default']
    MyHeader: typeof import('./src/components/layout/MyHeader.vue')['default']
    ProgressBar: typeof import('./src/components/Chart/ProgressBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableChart: typeof import('./src/components/Chart/TableChart.vue')['default']
    TableChartTest: typeof import('./src/components/Chart/TableChartTest.vue')['default']
    TaiwanMap: typeof import('./src/components/TaiwanMap.vue')['default']
    TaiwanVoteMap: typeof import('./src/components/Map/TaiwanVoteMap.vue')['default']
    Town: typeof import('./src/components/Map/Town.vue')['default']
  }
}
